name: Build

on:
  workflow_call:
  workflow_dispatch:
    branches: main

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Nuget restore
      run: nuget restore SimpleTest\SimpleTest.sln -Verbosity Detailed -NonInteractive -ConfigFile SimpleTest\nuget.config
    
    - name: Add msbuild to path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: msbuild SimpleTest\SimpleTest.sln /p:OutputPath=${{ github.workspace }}\_BuildScriptOutput /p:RestorePackages=false /p:GenerateProjectSpecificOutputFolder=true /p:OutDirWasSpecified=true
    
    - name: Run tests
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        vstest.console.exe _BuildScriptOutput\\SimpleTest\\SimpleTest.dll
      env:
        DEBUG: pw:channel:command,pw:channel:event,pw:channel:response
